// APP UI actions
export const ACTIVATE_CELL = "ACTIVATE_CELL";
export const TOGGLE_INTRO_COMPONENT = "TOGGLE_INTRO_COMPONENT";
export const TOGLE_GAME_RULES = "TOGLE_GAME_RULES";

// Sudoku game actions
export const SET_ACTIVE_CELL_STATE = "SET_ACTIVE_CELL_STATE";
export const SET_SUDOKU_STATE = "SET_SUDOKU_STATE";
export const SET_INVALID_CELLS = "SET_INVALID_CELLS";
export const SET_INVALID_ROWS = "SET_INVALID_ROWS";
export const SET_INVALID_COLUMNS = "SET_INVALID_COLUMNS";
export const SET_PUZZLE_AND_SOLVED_PUZZLE = "SET_PUZZLE_AND_SOLVED_PUZZLE";
export const SOLVE_PUZZLE = "SOLVE_PUZZLE";
export const SUDOKU_IS_SOLVED = " SUDOKU_IS_SOLVED";
export const SET_INVALID_BOXES_AND_NUMBERS = "SET_INVALID_BOXES_AND_NUMBERS";
export const SOLVE_SUDOKU_FOR_USER = "SOLVE_SUDOKU_FOR_USER";
export const SET_GAME_MODE = "SET_GAME_MODE";
export const INIT_USER_INPUT_SUDOKU_TO_SOLVE =
  "INIT_USER_INPUT_SUDOKU_TO_SOLVE";
export const SET_DIFFICULTY = "SET_DIFFICULTY";
export const CLEAR_ACTIVE_CELL = "CLEAR_ACTIVE_CELL";
